'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RC_ContractActionUser

    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''pnlAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdmin As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''lbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAdmin_SortCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdmin_SortCommand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Admin_ALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_ALL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_A As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_B As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_C As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_D As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_E As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_F As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_G As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_H control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_H As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_I As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_J control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_J As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_K As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_L As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_M As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_N As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_O As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_P As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_Q As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_R As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_S As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_T As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_U control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_U As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_V As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_W control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_W As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_X control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_X As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_Y As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Admin_Z control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Admin_Z As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstAdminUsersAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAdminUsersAll As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnAdminAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdminAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAdminRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdminRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstAdminUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstAdminUsers As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''pnlHeadquarters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeadquarters As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHQ_SortCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHQ_SortCommand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HQ_ALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_ALL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_A As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_B As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_C As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_D As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_E As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_F As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_G As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_H control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_H As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_I As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_J control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_J As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_K As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_L As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_M As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_N As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_O As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_P As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_Q As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_R As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_S As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_T As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_U control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_U As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_V As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_W control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_W As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_X control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_X As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_Y As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''HQ_Z control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HQ_Z As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstHeadquartersAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstHeadquartersAll As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnHeadquartersAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHeadquartersAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHeadquartersRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHeadquartersRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstHeadquarters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstHeadquarters As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''pnlNorthEast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNorthEast As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNE_SortCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNE_SortCommand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NE_ALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_ALL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_A As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_B As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_C As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_D As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_E As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_F As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_G As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_H control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_H As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_I As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_J control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_J As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_K As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_L As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_M As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_N As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_O As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_P As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_Q As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_R As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_S As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_T As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_U control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_U As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_V As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_W control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_W As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_X control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_X As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_Y As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NE_Z control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NE_Z As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstNorthEastAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstNorthEastAll As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnNorthEastAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNorthEastAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNorthEastRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNorthEastRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstNorthEast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstNorthEast As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''pnlNorthWest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNorthWest As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNW_SortCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNW_SortCommand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NW_ALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_ALL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_A As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_B As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_C As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_D As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_E As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_F As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_G As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_H control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_H As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_I As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_J control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_J As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_K As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_L As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_M As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_N As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_O As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_P As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_Q As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_R As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_S As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_T As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_U control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_U As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_V As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_W control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_W As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_X control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_X As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_Y As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''NW_Z control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NW_Z As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstNorthWestAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstNorthWestAll As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnNorthWestAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNorthWestAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNorthWestRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNorthWestRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstNorthWest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstNorthWest As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''pnlSouthWest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSouthWest As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSW_SortCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSW_SortCommand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SW_ALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_ALL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_A As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_B As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_C As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_D As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_E As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_F As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_G As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_H control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_H As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_I As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_J control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_J As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_K As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_L As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_M As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_N As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_O As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_P As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_Q As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_R As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_S As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_T As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_U control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_U As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_V As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_W control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_W As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_X control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_X As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_Y As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SW_Z control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SW_Z As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstSouthWestAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSouthWestAll As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnSouthWestAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSouthWestAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSouthWestRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSouthWestRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstSouthWest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSouthWest As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''pnlSouthEast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSouthEast As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSE_SortCommand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSE_SortCommand As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SE_ALL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_ALL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_A As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_B As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_C As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_D As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_E As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_F control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_F As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_G control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_G As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_H control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_H As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_I control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_I As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_J control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_J As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_K As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_L control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_L As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_M As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_N As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_O As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_P As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_Q control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_Q As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_R control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_R As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_S control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_S As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_T As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_U control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_U As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_V control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_V As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_W control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_W As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_X control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_X As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_Y control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_Y As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SE_Z control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SE_Z As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstSouthEastAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSouthEastAll As Global.Telerik.Web.UI.RadListBox

    '''<summary>
    '''btnSouthEastAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSouthEastAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSouthEastRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSouthEastRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstSouthEast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSouthEast As Global.Telerik.Web.UI.RadListBox
End Class
